generator:
  class:              sfPropelAdminGenerator
  param:
      model_class:      Cuenta
      theme:            default
      fields:
            nombre: { name: Nombre, params: size=64 }
            razon_social: { name: Raz&oacute;n Social , params: size=64 }
            cuit: { name: CUIT, params: size=11 }
            direccion: { name: Direcci&oacute;n , params: size=64 }
            ciudad: { name: Ciudad, params: size=64 }
            codigo_postal: { name: CP, params: size=20  }
            fk_provincia_id: { name: Provincia }
            fk_tipoiva_id: { name: Tipo Iva } 
            telefono: { name: Tel&eacute;fono, params: size=20 }
      list:
            title: Listado de Cuentas
            display: [ _nombre, razon_social, cuit, direccion, ciudad, codigo_postal, _tipo_iva, telefono ]
            object_actions:
                _edit: -
                _delete: -
                irCompleta:  { name: Agregar alumnos y responsables, action: verCompleta, icon: next.png }
            actions:
                _create: -
                
      edit:
            title: " "
            fields: 
                pais_id: {name: Pa√≠s }
            display: [ nombre, razon_social, cuit, direccion, ciudad, codigo_postal, _pais_id, _fk_provincia_id,  _fk_tipoiva_id, telefono ]
            actions:
                _delete: -
                _save: -
                _list: -
                _save_and_add: -